#!/bin/bash
SELF_DIR=$(realpath $(dirname ${BASH_SOURCE}))
TAG="isa"

if [[ $(arch) == 'arm64' ]]; then
  docker build -t "${TAG}" --platform linux/x86_64 "${SELF_DIR}"
else
  docker build -t "${TAG}" "${SELF_DIR}"
fi
