#!/bin/bash

SELF_DIR="$(realpath "$(dirname "${BASH_SOURCE}")")"
ARCH_FLAG=""
TAG="isa"

# detect architecture
if [[ $(arch) == 'arm64' ]]; then
  ARCH_FLAG="--platform linux/x86_64"
fi

docker build -t "${TAG}" $ARCH_FLAG "${SELF_DIR}"
